---
# This playbook prints a simple debug message
- name: Echo 
  hosts: all
  become: True

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Debug Morpheus user name
    debug:
      msg: "{{ lookup('env', 'USER') }}"
