---
# This playbook prints a simple debug message
- name: Echo 
  hosts: all
  become: True

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: username_on_the_host

  - debug: var=username_on_the_host
