#todo
   
- name: Install required packages for Ubuntu
  apt: 
    name: "{{ ad_packages_ubuntu }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: PIP install pexpect
  pip:
    name: pexpect
    state: latest

- name: Install realmd configuration file
  template:
    src: realmd.conf.j2
    dest: /etc/realmd.conf

- name: Join the Realm
  shell: echo "{{ realm_password }}"| realm join "{{ realm }}"
  ignore_errors: true
  register: realm_results

# - name: Print Realm Results
#   debug:
#     msg:
#       - "*********************"
#       - "*** Realm Results ***"
#       - "{{ realm_results }}"
#       - " "
#       - "*********************"
#       - "*** Group Results ***"
#       - "{{ group_results }}"
#   when: >
#     group_results

- name: Permit computer group
  expect:
    command: realm permit -g "{{ ansible_hostname }}"
    responses:
      Password for Administrator: "{{ realm_password }}"

- name: Permit root admins
  expect:
    command: realm permit -g "{{ root_admin_group }}"
    responses:
      Password for Administrator: "{{ realm_password }}"

- name: Add sssd conf lines
  lineinfile:
    path: /etc/sssd/sssd.conf
    line: "{{ item }}"
    state: present
    insertafter: '[{{ realm }}]'
  with_items:
    - 'ad_enable_gc = false'

- name: Replace Use fully qualified names
  replace:
    path: /etc/sssd/sssd.conf
    regexp: '^use_fully_qualified_names = True'
    replace: 'use_fully_qualified_names = false'
  notify: restart_sssd