- name: Add the Docker-CE reposoitory
  yum_repository:
    name: Docker-CE
    description: Docker-CE repo for CentOS
    enabled: True
    gpgcheck: False
    gpgkey: https://download.docker.com/linux/centos/gpg
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable

- name: Install Docker-CE
  package:
    name: "{{ docker_ce_packages }}"
    state: latest

- name: Start and Enable Docker service
  service: 
    name: docker
    state: started
    enabled: True 
